### ISSUE TITLE
第10章 ユーザーの更新・表示・削除

### ISSUE THREAD

**Issue by takanori-matsushita** [takanori-matsushita/rails-nuxt-practice#10]
branch: rails/updating-users

**Comment by takanori-matsushita** [comment]
**リスト 10.8: ユーザーのupdateアクションの初期実装**
app/controllers/users_controller.rb
```
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      render json: @user, status: :ok
    else
      render json: { error: @user.errors }, status: :unprocessable_entity
    end
  end
```

**Comment by takanori-matsushita** [comment]
**リスト 10.9: 編集の失敗に対するテスト green**
spec/requests/users_request_spec.rb
```
  it "unsuccessful edit" do
    patch user_path(@user),
    params: {
      user: {
        name:  "",
        email: "foo@invalid",
        password:              "foo",
        password_confirmation: "bar"
      }
    }
    expect(response.status).to eq 422
    json = JSON.parse(response.body)
    expect(json).to include "error"
  end
```

**Comment by takanori-matsushita** [comment]
**リスト 10.11: 編集の成功に対するテスト red**
spec/requests/users_request_spec.rb
```
  it "successful edit" do
    name  = "Foo Bar"
    email = "foo@bar.com"
    patch user_path(@user),
    params: {
      user: {
        name: name,
        email: email,
        password: "",
        password_confirmation: "",
      }
    }
    expect(response.status).to eq 200
    json = JSON.parse(response.body)
    expect(json).to include "name" => name
    expect(json).to include "email" => email
  end
```

**Comment by takanori-matsushita** [comment]
curlで実行してみる。
`curl -X PATCH "http://localhost:8000/users/1" -d "user[name]=Foobar&user[email]=foobar@railstutorial.org"`

以下のように編集できた。
```
{
    "id": 1,
    "name": "Foobar",
    "email": "foobar@railstutorial.org",
    "password_digest": "$2a$12$iVoOCVvxsTgd9yg3U7FQpe3Rmikjeu7JykM98fBZ1Y1nVPhnNqxDe",
    "created_at": "2020-06-16T07:26:19.201Z",
    "updated_at": "2020-06-19T17:05:30.999Z"
}
```

**Comment by takanori-matsushita** [comment]
**ユーザーにログインを要求する**
application_controllerに定義したauthorize_requestメソッドをbefore_actionに追加する。
app/controllers/users_controller.rb
```
class UsersController < ApplicationController
  before_action :authorize_request, only: [:update]
  : 
end
```

**Comment by takanori-matsushita** [comment]
before_actionを定義したことで、rspecのテストが通過しなくなった。
```
1) Users unsuccessful edit
     Failure/Error: expect(response.status).to eq 422
     
       expected: 422
            got: 401
     
       (compared using ==)
     # ./spec/requests/users_request_spec.rb:52:in `block (2 levels) in <main>'

  2) Users successful edit
     Failure/Error: expect(response.status).to eq 200
     
       expected: 200
            got: 401
     
       (compared using ==)
     # ./spec/requests/users_request_spec.rb:69:in `block (2 levels) in <main>'

Finished in 0.64783 seconds (files took 4.71 seconds to load)
16 examples, 2 failures
```

**Comment by takanori-matsushita** [comment]
ログインした状態でテストを通過できるように変更する。
spec/requests/users_request_spec.rb
```
  def authenticated_header(user)
    token = JsonWebToken.encode(user_id: user.id)
    { 'Authorization': "Bearer #{token}" }
  end
```
headerにトークンをもたせて更新処理を行う。
`patch user_path(@user), headers: authenticated_header(@user),`

これだと`users_request_spec.rb`でしかメソッドを使えないので、moduleとか作ってあげたら良さそう。

**Comment by takanori-matsushita** [comment]
以下の記事でmoduleを作成し、どのspecファイルでもメソッドを使えるようにできた。
[RSpecでヘルパーを作成する方法](https://breakthrough-tech.yuta-u.com/rspec/how-to-make-spec-support/)

**Comment by takanori-matsushita** [comment]
**リスト 10.34: indexアクションのテストをする**
spec/requests/users_request_spec.rb
```
  it "should redirect index when not logged in" do
    get users_path
    expect(response.status).to 401
  end
```

**Comment by takanori-matsushita** [comment]
**リスト 10.35: indexアクションにはログインを要求する green**
app/controllers/users_controller.rb
```
class UsersController < ApplicationController
  before_action :authorize_request, only: [:index, :update]
  
  def index
  end
  ~省略~
end
```

**Comment by takanori-matsushita** [comment]
**リスト 10.36: ユーザーのindexアクション**
app/controllers/users_controller.rb
```
  def index
    @users = User.secure
    render json: @users, status: :ok
  end
```

**Comment by takanori-matsushita** [comment]
curlコマンドで確認
`curl -X GET "http://localhost:8000/users" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE1OTI3NTM3NTN9.z5BrmpXhsQYviLV3BIIVVKoRQoCyIEUpNmEd0N9FxDM"`

**Comment by takanori-matsushita** [comment]
**リスト 10.44: paginationはkaminariを利用する**
Gemfile
`gem 'kaminari'`
`make bundle`でインストール

**Comment by takanori-matsushita** [comment]
**リスト 10.46: indexアクションでUsersをページネートする**
app/controllers/users_controller.rb
```
  def index
    @users = User.secure.page(params[:page]).per(30)
    render json: @users, status: :ok
  end
```

**Comment by takanori-matsushita** [comment]
**リスト 10.48: ページネーションを含めたUsersIndexのテスト**
spec/requests/users_request_spec.rb
```
it "index including pagination" do
    get users_path, headers: authenticated_header(@user)
    expect(response.status).to eq 200
    json = JSON.parse(response.body)
    binding.irb
    expect(json.length).to eq 30
```

**Comment by takanori-matsushita** [comment]
エラー発生。
jsonの数が1しかない。テストデータを入れていなかったので、FactoryBotでデータを追加・修正する。
spec/factories/user.rb
```
FactoryBot.define do
  factory :michael, class: User do
    name { "Michael Example" }
    email { "michael@example.com" }
    password { "password" }
    password_confirmation { "password" }
  end
  
  factory :sterling, class: User do
    name { "Sterling Archer" }
    email { "sterling@example.gov" }
    password { "password" }
    password_confirmation { "password" }
  end
  
  factory :lana, class: User do
    name { "Lana Kane" }
    email { "lana@example.gov" }
    password { "password" }
    password_confirmation { "password" }
  end
  
  factory :malory, class: User do
    name { "Malory Archer" }
    email { "malory@example.gov" }
    password { "password" }
    password_confirmation { "password" }
  end
  
  30.times do |n|
    factory "users#{n}".to_sym, class: User do
      name { "User#{n}" }
      email { "user-#{n}@example.com" }
      password { "password" }
      password_confirmation { "password" }
    end
  end
end
```

**Comment by takanori-matsushita** [comment]
テストごとにデータがかぶって登録できないエラーが出ているため、Database Cleanerを導入する。
Gemfile
```
group :development, :test do
  gem 'database_cleaner'
end
```
`make bundle`

**Comment by takanori-matsushita** [comment]
rails_helper.rbに以下を記述
spec/rails_helper.rb
```
RSpec.configure do |config|
  : 
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.around(:each) do |example|
    DatabaseCleaner.cleaning do
      example.run
    end
  end
  : 
end
```
[Rspec3.1のbefore,afterフックが実行されるタイミング](https://qiita.com/syunk38/items/e6cc1282c5479555f748)
[Rspec導入時のDatabaseCleanerの設定](https://kossy-web-engineer.hatenablog.com/entry/2018/11/02/080035)

**Comment by takanori-matsushita** [comment]
**リスト 10.55: サンプルデータ生成タスクに管理者を1人追加する**
spec/factories/user.rb
```
FactoryBot.define do
  factory :michael, class: User do
    name { "Michael Example" }
    email { "michael@example.com" }
    password { "password" }
    password_confirmation { "password" }
    admin { true }
  end
  : 
end
```

**Comment by takanori-matsushita** [comment]
**リスト 10.56: admin属性の変更が禁止されていることをテストする**
spec/requests/users_request_spec.rb
```
  it "should not allow the admin attribute to be edited via the web" do
    patch user_path(@other_user), headers: authenticated_header(@other_user),
    params: {
      user: {
        password: "foobar",
        password_confirmation: "foobar",
        admin: true
      }
    }
    expect(@other_user.admin).to_not be_truthy
  end
```

**Comment by takanori-matsushita** [comment]
**リスト 10.58: 実際に動作するdestroyアクションを追加する**
app/controllers/users_controller.rb
```
  def destroy
    if @current_user.admin?
      User.find(params[:id]).destroy
      return render json: { success: "user deleted" }, status: :ok
    end
    render json: { error: "no admin rights" }, status: :unauthorized
  end
```

**Comment by takanori-matsushita** [comment]
**リスト 10.61: 管理者権限の制御をアクションレベルでテストする green**
spec/requests/users_request_spec.rb
```
  it "should redirect destroy when not logged in" do
    expect{
      delete user_path(@user)
    }.to_not change(User, :count)
  end

  it"should redirect destroy when logged in as a non-admin" do
    expect{
      delete user_path(@user), headers: authenticated_header(@other_user)
    }.to_not change(User, :count)
  end
```

**Comment by takanori-matsushita** [comment]
リスト 10.62: ユーザー削除に対するテスト
spec/requests/users_request_spec.rb
```
  it "should destroy when logged in as a admin" do
    expect{
      delete user_path(@other_user), headers: authenticated_header(@user)
    }.to change(User, :count).by(-1)
  end
```

**Comment by takanori-matsushita** [comment]
curlコマンドでID＝10のユーザーを削除する
`curl -X DELETE 'http://localhost:8000/users/10' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE1OTI3NTM3NTN9.z5BrmpXhsQYviLV3BIIVVKoRQoCyIEUpNmEd0N9FxDM'
`
